### ISSUE TITLE
2024.1.1 Release Checklist

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#570]
Here is a list of all the things that need to be done to release 2024.1.1

- [x] Write Update Post
- [x] verify features in post have tests and documentation
  - [x] plugins have tests #575 
  - [x] plugins have documentation #571 
  - [x] #577
  - [x] #583
- [X] release rc2
- Update docs and tests of
  - [x] #587
  - [x] #588
  - [x] #589
  - [x] #590
  - [x] (document) init using cookiecutter
  
- [ ] publish with gh release create 2024.1.1 --generate-notes --notes-start-tag 2023.10.4

- Current Discussion: https://github.com/render-engine/render-engine/discussions/568
