### ISSUE TITLE
TEST: Implement new Feature

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#598]

**Comment by kjaymiller** [comment]
sounds good

BOT: 
- [ ] Create ISSUE code for feature #598
- [ ] Create Docs for feature #598
- [ ] Create tests for feature #598
