### ISSUE TITLE
[EPIC] Changes for Maintainers

### ISSUE THREAD

**Issue by kjaymiller** [render-engine/render-engine#827]
Using the phrase epic here as it will be a larger issue with many issues attached to it. 

#### The Problem

Our current Pull Requests template serves well for getting information needed for changes. However, it's starting to feel like many folks are beginning to use AI to solve these issues. 

This is fine however there is an issue in that AI generated code begins to lack context and understanding for choices made.

**TO BE CLEAR:** I'm not saying that AI cannot be used to implement code. I'm only saying that solving the issue is only a part of the challenge. We need to ensure that solving the immediate issue continues to support the ecosystem that is being built and the decisions being made are congruent with the design of the platform.

In order to resolve this issue, I'm making some changes that I think should be implmented BEFORE there is any further development on this project.

I'm also going to be making these recommendations for other projects that I own as well.

- [ ] Create a platform design document
- [ ] Enforce more verbose Pull Requests
- [ ] Require a conversation to be had with beyond I would like to work on this issue
  - [ ] Update `Contributor.md` these instructions
  - [ ] Create `Maintainers.md` documentation that should entail how Issues should be triaged and labeled and how PRs should be reviewed.
